INSERT INTO JOB_APPLICATION
(COMPANY_NAME, ROLE_TITLE, STATUS, SALARY_RANGE, APPLIED_DATE, FOLLOW_UP_DATE, NOTES)
VALUES
('Google', 'Software Engineer Intern', 'APPLIED', '$35/hr',
'2026-05-01', '2026-05-10',
'Applied through careers portal');

INSERT INTO JOB_APPLICATION
(COMPANY_NAME, ROLE_TITLE, STATUS, SALARY_RANGE, APPLIED_DATE, FOLLOW_UP_DATE, NOTES)
VALUES
('Amazon', 'Backend Developer', 'INTERVIEWING', '$120k',
'2026-04-20', '2026-05-15',
'Completed first technical interview');

INSERT INTO JOB_APPLICATION
(COMPANY_NAME, ROLE_TITLE, STATUS, SALARY_RANGE, APPLIED_DATE, FOLLOW_UP_DATE, NOTES)
VALUES
('Microsoft', 'Cloud Engineer', 'SCREENING', '$110k',
'2026-05-03', '2026-05-12',
'Recruiter phone screening scheduled');